chore: restful api display smux and mptcp
MetaCubeX/mihomo pull request #1646
Opened 2024-11-08 17:29 UTC by chenx-dust

Tested with my own config.

2024-11-12 07:54 UTC, H1JK requested changes

2024-11-12 07:54 UTC, H1JK commented on adapter/outbound/base.go
> +// SupportTFO implements C.ProxyAdapter
Please fix the comment.

2024-11-12 07:59 UTC, chenx-dust commented on adapter/outbound/base.go
> +// SupportTFO implements C.ProxyAdapter
Fixed. Thanks!

2024-11-14 02:06 UTC, H1JK approved these changes

2024-11-14 02:08 UTC, merged